### ISSUE TITLE
[IDEA] - Mongo DB integration & Heroku hosting

### ISSUE THREAD

**Issue by CatalaHD** [CatalaHD/CataBot#100]
See more info [here](https://www.youtube.com/watch?v=8no3SktqagY)

**Comment by CatalaHD** [comment]
TODO:

- [ ] DB Creation and installation
- [ ] Heroku hosting
- [ ] Env with [this tutorial](https://www.youtube.com/watch?v=gT_1c9YFffk)

**Comment by CatalaHD** [comment]
Al local funciona, pero a Heroku no. Log:
```
2021-02-23T00:04:57.573433+00:00 app[api]: Release v24 created by user afj.99@hotmail.com
2021-02-23T00:05:05.000000+00:00 app[api]: Build succeeded
2021-02-23T00:05:39.924856+00:00 app[api]: Set maintenance mode off by user afj.99@hotmail.com
2021-02-23T00:06:08.468810+00:00 app[api]: Scaled to web@0:Free worker@1:Free by user afj.99@hotmail.com
2021-02-23T00:06:13.367059+00:00 heroku[worker.1]: Starting process with command `npm start`
2021-02-23T00:06:13.957429+00:00 heroku[worker.1]: State changed from starting to up
2021-02-23T00:06:16.035428+00:00 app[worker.1]: 
2021-02-23T00:06:16.035442+00:00 app[worker.1]: > catabot@1.3.1 start
2021-02-23T00:06:16.035442+00:00 app[worker.1]: > node app.js
2021-02-23T00:06:16.035443+00:00 app[worker.1]: 
2021-02-23T00:06:18.784318+00:00 app[worker.1]: 🦙Llamas al poder🦙: 24 members
2021-02-23T00:06:28.680397+00:00 app[worker.1]: MongooseError: Operation `servers.updateOne()` buffering timed out after 10000ms
2021-02-23T00:06:28.680416+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.680418+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.680419+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.680545+00:00 app[worker.1]: DB: Actualitzat server 🦙Llamas al poder🦙 correctament!
2021-02-23T00:06:28.791400+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.791402+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.791403+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.791403+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.791742+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.791743+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.791744+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.791744+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.793224+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.793226+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.793226+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.793226+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.793693+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.793694+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.793695+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.793695+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.795167+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.795168+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.795169+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.795169+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.796702+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.796703+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.796703+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.796704+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.797092+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.797093+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.797094+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.797094+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.797524+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.797525+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.797525+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.797526+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.797861+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.797861+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.797862+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.797863+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.798191+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.798192+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.798192+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.798193+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.799631+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.799632+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.799632+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.799633+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.799935+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.799935+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.799936+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.799936+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.800237+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.800238+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.800239+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.800240+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.801665+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.801666+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.801667+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.801667+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.801899+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.801901+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.801901+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.801902+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.802146+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.802147+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.802148+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.802148+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.802415+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.802416+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.802418+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.802418+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.802742+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.802744+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.802744+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.802745+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.804267+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.804268+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.804269+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.804270+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.804544+00:00 app[worker.1]: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
2021-02-23T00:06:28.804545+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.804545+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.804546+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.806577+00:00 app[worker.1]: (node:21) UnhandledPromiseRejectionWarning: MongooseError: Operation `servers.findOne()` buffering timed out after 10000ms
2021-02-23T00:06:28.806578+00:00 app[worker.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
2021-02-23T00:06:28.806579+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-02-23T00:06:28.806579+00:00 app[worker.1]:     at processTimers (internal/timers.js:497:7)
2021-02-23T00:06:28.806674+00:00 app[worker.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-02-23T00:06:28.806763+00:00 app[worker.1]: (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-02-23T00:06:48.171608+00:00 app[worker.1]: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
2021-02-23T00:06:48.171619+00:00 app[worker.1]:     at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:845:32)
2021-02-23T00:06:48.171620+00:00 app[worker.1]:     at /app/node_modules/mongoose/lib/index.js:345:10
2021-02-23T00:06:48.171621+00:00 app[worker.1]:     at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
2021-02-23T00:06:48.171622+00:00 app[worker.1]:     at new Promise (<anonymous>)
2021-02-23T00:06:48.171623+00:00 app[worker.1]:     at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
2021-02-23T00:06:48.171624+00:00 app[worker.1]:     at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1135:10)
2021-02-23T00:06:48.171624+00:00 app[worker.1]:     at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:344:20)
2021-02-23T00:06:48.171624+00:00 app[worker.1]:     at Object.<anonymous> (/app/app.js:384:10)
2021-02-23T00:06:48.171625+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-02-23T00:06:48.171626+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-02-23T00:06:48.171626+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-02-23T00:06:48.171626+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-02-23T00:06:48.171627+00:00 app[worker.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
2021-02-23T00:06:48.171627+00:00 app[worker.1]:     at internal/main/run_main_module.js:17:47 {
2021-02-23T00:06:48.171628+00:00 app[worker.1]:   reason: TopologyDescription {
2021-02-23T00:06:48.171628+00:00 app[worker.1]:     type: 'ReplicaSetNoPrimary',
2021-02-23T00:06:48.171629+00:00 app[worker.1]:     setName: null,
2021-02-23T00:06:48.171629+00:00 app[worker.1]:     maxSetVersion: null,
2021-02-23T00:06:48.171630+00:00 app[worker.1]:     maxElectionId: null,
2021-02-23T00:06:48.171630+00:00 app[worker.1]:     servers: Map {
2021-02-23T00:06:48.171630+00:00 app[worker.1]:       'cluster0-shard-00-01.0hmvb.mongodb.net:27017' => [ServerDescription],
2021-02-23T00:06:48.171631+00:00 app[worker.1]:       'cluster0-shard-00-02.0hmvb.mongodb.net:27017' => [ServerDescription],
2021-02-23T00:06:48.171631+00:00 app[worker.1]:       'cluster0-shard-00-00.0hmvb.mongodb.net:27017' => [ServerDescription]
2021-02-23T00:06:48.171632+00:00 app[worker.1]:     },
2021-02-23T00:06:48.171632+00:00 app[worker.1]:     stale: false,
2021-02-23T00:06:48.171633+00:00 app[worker.1]:     compatible: true,
2021-02-23T00:06:48.171634+00:00 app[worker.1]:     compatibilityError: null,
2021-02-23T00:06:48.171634+00:00 app[worker.1]:     logicalSessionTimeoutMinutes: null,
2021-02-23T00:06:48.171634+00:00 app[worker.1]:     heartbeatFrequencyMS: 10000,
2021-02-23T00:06:48.171635+00:00 app[worker.1]:     localThresholdMS: 15,
2021-02-23T00:06:48.171635+00:00 app[worker.1]:     commonWireVersion: null
2021-02-23T00:06:48.171635+00:00 app[worker.1]:   }
2021-02-23T00:06:48.171635+00:00 app[worker.1]: }
```

**Comment by CatalaHD** [comment]
Era perque Heroku no tenia una IP valida, ja funciona WIIIIIIIII 😄
