### ISSUE TITLE
[BUG] - voice_channel of undefined al sortir del canal de veu 

### ISSUE THREAD

**Issue by CatalaHD** [CatalaHD/CataBot#134]
```
 Jun 01 18:07:33 catabot app/worker.1 --- Nova comanda ---
 Jun 01 18:07:33 catabot app/worker.1 Autor: <@300983337617719297> - catalufo#8772
 Jun 01 18:07:33 catabot app/worker.1 Contingut: !playlist https://youtube.com/playlist?list=PLsvRJlLlDt00j2F0ke-tSrZpErc9vnEE3
 Jun 01 18:07:33 catabot app/worker.1 Servidor: LegiÀ Masters
 Jun 01 18:07:33 catabot app/worker.1 Canal: bot
 Jun 01 18:13:11 catabot app/worker.1 --- Nova comanda ---
 Jun 01 18:13:11 catabot app/worker.1 Autor: <@300983337617719297> - catalufo#8772
 Jun 01 18:13:11 catabot app/worker.1 Contingut: !playnow OQUES GRASSES - VIDA D'OFERTA
 Jun 01 18:13:11 catabot app/worker.1 Servidor: LegiÀ Masters
 Jun 01 18:13:11 catabot app/worker.1 Canal: bot
 Jun 01 18:44:11 catabot app/worker.1 /app/lib/musicModule.js:107
 Jun 01 18:44:11 catabot app/worker.1   embed.setDescription(`Desconnectant del canal de veu ${song_queue.voice_channel}.`);
 Jun 01 18:44:11 catabot app/worker.1                                                                     ^
 Jun 01 18:44:11 catabot app/worker.1 TypeError: Cannot read property 'voice_channel' of undefined
 Jun 01 18:44:11 catabot app/worker.1     at esborrar (/app/lib/musicModule.js:107:69)
 Jun 01 18:44:11 catabot app/worker.1     at VoiceConnection.<anonymous> (/app/lib/musicModule.js:79:7)
 Jun 01 18:44:11 catabot app/worker.1     at VoiceConnection.emit (events.js:388:22)
 Jun 01 18:44:11 catabot app/worker.1     at VoiceConnection._disconnect (/app/node_modules/discord.js/src/client/voice/VoiceConnection.js:373:10)
 Jun 01 18:44:11 catabot app/worker.1     at VoiceConnection.disconnect (/app/node_modules/discord.js/src/client/voice/VoiceConnection.js:359:10)
 Jun 01 18:44:11 catabot app/worker.1     at VoiceChannel.leave (/app/node_modules/discord.js/src/structures/VoiceChannel.js:146:69)
 Jun 01 18:44:11 catabot app/worker.1     at Timeout.sortir [as _onTimeout] (/app/lib/musicModule.js:102:28)
 Jun 01 18:44:11 catabot app/worker.1     at listOnTimeout (internal/timers.js:557:17)
 Jun 01 18:44:11 catabot app/worker.1     at processTimers (internal/timers.js:498:7)
 Jun 01 18:44:11 catabot heroku/worker.1 Process exited with status 1
```

**Comment by CatalaHD** [comment]
Un altre error

```
Jun 07 21:35:17 catabot app/worker.1 (node:21) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'voice_channel' of undefined
 Jun 07 21:35:17 catabot app/worker.1     at esborrar (/app/lib/musicModule.js:107:69)
 Jun 07 21:35:17 catabot app/worker.1     at VoiceConnection.<anonymous> (/app/lib/musicModule.js:79:7)
 Jun 07 21:35:17 catabot app/worker.1     at VoiceConnection.emit (events.js:388:22)
 Jun 07 21:35:17 catabot app/worker.1     at VoiceConnection._disconnect (/app/node_modules/discord.js/src/client/voice/VoiceConnection.js:373:10)
 Jun 07 21:35:17 catabot app/worker.1     at VoiceConnection.disconnect (/app/node_modules/discord.js/src/client/voice/VoiceConnection.js:359:10)
 Jun 07 21:35:17 catabot app/worker.1     at VoiceChannel.leave (/app/node_modules/discord.js/src/structures/VoiceChannel.js:146:69)
 Jun 07 21:35:17 catabot app/worker.1     at sortir (/app/lib/musicModule.js:102:28)
 Jun 07 21:35:17 catabot app/worker.1     at video_player (/app/lib/musicModule.js:117:12)
 Jun 07 21:35:17 catabot app/worker.1     at StreamDispatcher.<anonymous> (/app/lib/musicModule.js:144:9)
 Jun 07 21:35:17 catabot app/worker.1     at StreamDispatcher.emit (events.js:388:22)
 Jun 07 21:35:17 catabot app/worker.1     at finish (internal/streams/writable.js:657:10)
 Jun 07 21:35:17 catabot app/worker.1     at finishMaybe (internal/streams/writable.js:644:9)
 Jun 07 21:35:17 catabot app/worker.1     at internal/streams/writable.js:617:7
 Jun 07 21:35:17 catabot app/worker.1     at StreamDispatcher._final (/app/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:248:5)
 Jun 07 21:35:17 catabot app/worker.1     at callFinal (internal/streams/writable.js:610:10)
 Jun 07 21:35:17 catabot app/worker.1     at processTicksAndRejections (internal/process/task_queues.js:82:21)
 Jun 07 21:35:17 catabot app/worker.1 (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```
