### ISSUE TITLE
[BUG] - Mirar quan es canvia el apodo del bot i posar-lo amb un catch() al on.('ready')

### ISSUE THREAD

**Issue by CatalaHD** [CatalaHD/CataBot#138]
```
(node:21) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
 Jun 08 01:39:49 catabot app/worker.1     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
 Jun 08 01:39:49 catabot app/worker.1     at runMicrotasks (<anonymous>)
 Jun 08 01:39:49 catabot app/worker.1     at processTicksAndRejections (internal/process/task_queues.js:95:5)
 Jun 08 01:39:49 catabot app/worker.1     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
 Jun 08 01:39:49 catabot app/worker.1     at async GuildMember.edit (/app/node_modules/discord.js/src/structures/GuildMember.js:312:5)
 Jun 08 01:39:49 catabot app/worker.1 (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 Jun 08 01:39:49 catabot app/worker.1 (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by CatalaHD** [comment]
Fixed on the last commit d95d2bc6589e10d7d7d7a6a11dbbae47d655845f
