### ISSUE TITLE
[BUG] - La "SomeRandomAPI" està fallant, avisa

### ISSUE THREAD

**Issue by CatalaHD** [CatalaHD/CataBot#80]
En quant es posa la comanda
`!poke pikachu`
El bot no respon i treu aquest missatge per consola
```
(node:3897) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substring' of undefined
    at /home/ubuntu/CataBOT/commands/Entreteniment/pokedex.js:46:56
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3897) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3897) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Això passa perque la API no respon res mentres està en manteniment.

Es podria fer
----
Si la resposta es null => respondre "LA API NO ESTÀ DISPONIBLE EN AQUEST MOMENT"

**Comment by CatalaHD** [comment]
El problema no és la de API, sino de que han cambiat la resposta i ara s'agafa de diferent manera.
S'estan provant solucions al problema

**Comment by CatalaHD** [comment]
Ara ha tornat a fallar amb la pokedex. Tot el rato la estan canviant.
Ara ja funciona en tots els casos i és estable
